In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
# test code

# 1. Load Data

In [38]:
data = pd.read_csv('../data/raw/dataTp2.csv')
data.head()

,Unnamed: 0,valence_intensity,fear_intensity,anger_intensity,happiness_intensity,sadness_intensity,sentiment
0,2157,0.501000,0.405000,0.407000,0.320000,0.365000,0
1,1223,0.497667,0.427000,0.408667,0.290000,0.378333,0
2,1083,0.460600,0.439800,0.421000,0.308400,0.406600,0
3,456,0.498000,0.454000,0.386000,0.379000,0.402000,0
4,1448,0.458818,0.483091,0.406909,0.297818,0.395273,0

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           30000 non-null  int64
 1   valence_intensity    30000 non-null  float64
 2   fear_intensity       30000 non-null  float64
 3   anger_intensity      30000 non-null  float64
 4   happiness_intensity  30000 non-null  float64
 5   sadness_intensity    30000 non-null  float64
 6   sentiment            30000 non-null  int64
dtypes: float64(5), int64(2)
memory usage: 1.6 MB

In [40]:
data.shape

(30000, 7)

In [41]:
data.drop(columns=['Unnamed: 0'], inplace=True)

In [42]:
data.head()

,valence_intensity,fear_intensity,anger_intensity,happiness_intensity,sadness_intensity,sentiment
0,0.501000,0.405000,0.407000,0.320000,0.365000,0
1,0.497667,0.427000,0.408667,0.290000,0.378333,0
2,0.460600,0.439800,0.421000,0.308400,0.406600,0
3,0.498000,0.454000,0.386000,0.379000,0.402000,0
4,0.458818,0.483091,0.406909,0.297818,0.395273,0

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   valence_intensity    30000 non-null  float64
 1   fear_intensity       30000 non-null  float64
 2   anger_intensity      30000 non-null  float64
 3   happiness_intensity  30000 non-null  float64
 4   sadness_intensity    30000 non-null  float64
 5   sentiment            30000 non-null  int64
dtypes: float64(5), int64(1)
memory usage: 1.4 MB

In [44]:
data.describe()

,valence_intensity,fear_intensity,anger_intensity,happiness_intensity,sadness_intensity,sentiment
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.00000
mean,0.477280,0.435327,0.423444,0.311358,0.399372,0.00000
std,0.082379,0.082018,0.075165,0.081321,0.068110,0.81651
min,0.091000,0.113000,0.142000,0.008000,0.145000,-1.00000
25%,0.432000,0.381937,0.374800,0.265000,0.356383,-1.00000
50%,0.486000,0.433500,0.414000,0.314000,0.392000,0.00000
75%,0.527000,0.484000,0.463000,0.359000,0.433571,1.00000
max,0.860000,0.850000,0.860000,0.771000,0.833000,1.00000

In [45]:
data['sentiment'].value_counts()

sentiment
 0    10000
-1    10000
 1    10000
Name: count, dtype: int64

In [46]:
data.to_csv('../data/processed/data.csv', index=False)

In [49]:
new_data = pd.read_csv('../data/processed/data.csv')
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   valence_intensity    30000 non-null  float64
 1   fear_intensity       30000 non-null  float64
 2   anger_intensity      30000 non-null  float64
 3   happiness_intensity  30000 non-null  float64
 4   sadness_intensity    30000 non-null  float64
 5   sentiment            30000 non-null  int64
dtypes: float64(5), int64(1)
memory usage: 1.4 MB